export const featuredPortfolio = [
  {
    id: 1,
    title: "packagecloud",
    img: "assets/pcweb.png",
    desc: "A cloud-based package repository service. Provided frontend support such as page builds, A/B testing, mobile responsiveness additions, and design implementation as well as customer-facing user support.",
    tech: "HTML/CSS, Ruby, Sass",
    link: "https://packagecloud.io/",
  },
  {
    id: 2,
    title: "CSS Art & Creative Css",
    img: "assets/cssart.png",
    desc: "Talk given about my strategies as an artist specializing in traditional media making CSS art for the first time. A highly reccommended wild ride of fun art, process details, and easy-to-follow instructions.",
    tech: "HTML/CSS, patience",
    link: "https://www.youtube.com/watch?v=jbHVNn4qoPI",
  },
  {
    id: 3,
    title: "overcast",
    img: "assets/overcast.png",
    desc: "Music-playing app that generates playlists based on weather at user's location & genre choice. Made as Tech Lead of a team of five engineers in partnership with Rakuten RapidAPI.",
    tech: "React/Redux, NodeJS/Express, PostgreSQL, HTML/CSS",
    link: "https://github.com/Overcast-CC11/overcast",
  },
  {
    id: 4,
    title: "MetricFire",
    img: "assets/mf1.png",
    desc: "Design implementation for user dashboard and onboarding process for users of application monitoring platform. Worked with new languages, interpreted legacy code, incorporated Sass, implemented designs and animations.",
    tech: "HTML/CSS/SASS, CoffeeScript, JavaScript, PHP",
    link: "https://metricfire.com",
  },
  {
    id: 5,
    title: "destiNations",
    img: "assets/dest.png",
    desc: "An educational, interactive mobile app that displays real flight paths and the planes' destination countries. Features a passport to collect countries visited, a scavenger hunt to learn country facts, and 3D graphics rendered by yours truly! Made as Frontend Lead in a team of five engineers.",
    tech: "Unity/C#, Node.js/Express, Firebase",
    link: "https://github.com/cinnamon-buns/destiNations-front/",
  },
  {
    id: 6,
    title: "YWCA",
    img: "assets/ywca.png",
    desc: "Website build and continued maintenance for YWCA Stand Against Racism and A Week Without Violence. Work done on event search and result listing, styling, and mobile responsiveness.",
    tech: "HTML/CSS/SASS, WordPress, JavaScript, PHP",
    link: "https://standagainstracism.org/all-events",
  },
];

export const Portfolio2 = [
  {
    id: 1,
    title: "KNIGHTS ONLY",
    img: "assets/knightsonly.png",
    desc: "Web app that draws you, a knight, a personal crest based on your answers to various word association questions. Images are drawn and added to question by question on HTML canvas.",
    tech: "Vue, Node.js, HTML/CSS",
    link: "https://github.com/caxwel/personal-crest-designer",
  },
  {
    id: 2,
    title: "overcast",
    img: "assets/overcast.png",
    desc: "Music-playing app that generates playlists based on weather at user's location & genre choice. Made as Tech Lead of a team of five engineers in partnership with Rakuten RapidAPI.",
    tech: "React/Redux, NodeJS/Express, PostgreSQL, HTML/CSS",
    link: "https://github.com/Overcast-CC11/overcast",
  },
  {
    id: 3,
    title: "destiNations",
    img: "assets/dest.png",
    desc: "An educational, interactive mobile app that displays real flight paths and the planes' destination countries. Features a passport to collect countries visited, a scavenger hunt to learn country facts, and 3D graphics rendered by yours truly! Made as Frontend Lead in a team of five engineers.",
    tech: "Unity/C#, Node.js/Express, Firebase",
    link: "https://github.com/cinnamon-buns/destiNations-front/",
  },
  {
    id: 4,
    title: "CSS Art & Creative Css",
    img: "assets/cssart.png",
    desc: "Talk given about my strategies as an artist specializing in traditional media making CSS art for the first time. A highly reccommended wild ride of fun art, process details, and easy-to-follow instructions.",
    tech: "HTML/CSS, patience",
    link: "https://www.youtube.com/watch?v=jbHVNn4qoPI",
  },
  {
    id: 5,
    title: "Crypticgen",
    img: "assets/crypticgen.png",
    desc: "Personal solo project of a web app that genenerates interesting writing prompts from a database of unusual statements, with option to share to twitter.",
    tech: "HTML/CSS, PostgreSQL",
    link: "https://github.com/caxwel/crypticgen",
  },
  {
    id: 6,
    title: "starfield",
    img: "assets/starfield.png",
    desc: "Interactive project built in Unity/C# over the course of a week with the goal of rapidly learning new technologies and languages.",
    tech: "Unity/C#",
    link: "https://github.com/caxwel/star-field",
  },
];

export const Portfolio1 = [
  {
    id: 1,
    title: "packagecloud",
    img: "assets/pcweb.png",
    desc: "A cloud-based package repository service. Provided frontend support such as page builds, A/B testing, mobile responsiveness additions, and design implementation as well as customer-facing user support.",
    tech: "HTML/CSS, Ruby, Sass",
    link: "https://packagecloud.io/",
  },
  {
    id: 2,
    title: "MetricFire",
    img: "assets/mf1.png",
    desc: "Design implementation for user dashboard and onboarding process for users of application monitoring platform. Worked with new languages, interpreted legacy code, incorporated Sass.",
    tech: "HTML/CSS/SASS, CoffeeScript, JavaScript, PHP",
    link: "https://metricfire.com",
  },
  {
    id: 3,
    title: "treehouse",
    img: "assets/treehouse.png",
    desc: "Database organization, admin page structuring, and design implementation for startup online coding school. Interpreted legacy code, worked with an international team, discerned and presented on structure for new team members.",
    tech: "HTML/CSS/SASS, Ruby, JavaScript",
    link: "https://teamtreehouse.com",
  },
  {
    id: 4,
    title: "YWCA",
    img: "assets/ywca.png",
    desc: "Website build and continued maintenance for YWCA Stand Against Racism and A Week Without Violence. Work done on event search and result listing, styling, and mobile responsiveness.",
    tech: "HTML/CSS/SASS, WordPress, JavaScript, PHP",
    link: "https://standagainstracism.org/all-events",
  },
  {
    id: 5,
    title: "BIDMC Where Extraordinary Lives",
    img: "assets/bidmc.png",
    desc: "Page build, scripted component creation, styling, and responsiveness edits for Beth Israel Deaconess Medical Center's event unveiling of their new building.",
    tech: "HTML/CSS/SASS, WordPress, JavaScript, PHP",
    link: "https://whereextraordinarylives.org",
  },
  {
    id: 6,
    title: "The Nature Conservancy",
    img: "assets/tnc.png",
    desc: "Website build for The Nature Conservancy, built as part of a larger team. Front end work done such as page builds, custom scripting, and meeting accessibility standards.",
    tech: "HTML/CSS/SASS, JavaScript, Engaging Networks, AAA Accessibility",
    link: "https://nature.org",
  },
  // {
  //   id: 7,
  //   title: "Diabetes Canada Lace Up",
  //   img: "assets/laceup.png",
  //   desc: "Stylesheet and page/component build for Diabetes Canada's event pages. Created a full SASS stylesheet and many HTML page templates using mobile-first design.",
  //   tech: "HTML/CSS/SASS, JavaScript",
  //   link: "https://crm2.diabetes.ca/site/SPageNavigator/2021_laceup_home.html",
  // },
];

export const descriptions = [
  {
    id: "1",
    icon: "assets/overcastlogo.png",
    title: "overcast",
    desc: "Music-playing app that generates playlists based on weather at user's location & genre choice.",
    desc2:
      "Made as Tech Lead of a team of five engineers in partnership with Rakuten RapidAPI.",
    img: "assets/overm.png",
  },
  {
    id: "2",
    icon: "assets/pclogo.png",
    title: "packagecloud",
    desc: "Mobile and web development done for package hosting product.",
    desc2: "Contributions include mobile responsiveness, page builds, and design implementation as well as user support.",
    img: "assets/pc1.png",
  },
  {
    id: "3",
    icon: "assets/mflogo.png",
    title: "metricfire",
    desc: "Frontend web development done for onboarding process of application monitoring service.",
    desc2: "Contributions include page builds and design implementation.",
    img: "assets/mf2.png",
  },
  {
    id: "4",
    icon: "assets/moongift.gif",
    title: "CSS Art & Creative Css",
    desc: "Talk given about my strategies as an artist specializing in traditional media making CSS art for the first time.",
    desc2:
      "A highly reccommended wild ride of fun art, process details, and easy-to-follow instructions.",
    img: "assets/cssart.png",
  },
  {
    id: "5",
    icon: "assets/treehouselogo.png",
    title: "treehouse",
    desc: "Web development and database organization for startup online coding school.",
    desc2: "Both frontend and backend contributions made for product in development.",
    img: "assets/treehouse2.png",
  },
  {
    id: "6",
    icon: "assets/destinationslogo.png",
    title: "destiNations",
    desc: "An educational, interactive mobile app that displays real flight paths and the planes' destination countries.",
    desc2:
      "Features a passport to collect countries visited, a scavenger hunt to learn country facts, and 3D graphics rendered by yours truly! Made as Frontend Lead in a team of five engineers.",
    img: "assets/destm.png",
  },
  {
    id: "7",
    icon: "assets/moont.png",
    title: "KNIGHTS ONLY",
    desc: "Web app that draws you, a knight, a personal crest based on your answers to various word association questions.",
    desc2: "Images are drawn and added to question by question on HTML canvas.",
    img: "assets/knightsm.png",
  },
];
